const EtlTableInfoType = {
  ETL_INFO_FETCH_SUCCESS: "ETL_INFO_FETCH_SUCCESS",
  ETL_INFO_FETCH_ERROR: "ETL_INFO_FETCH_ERROR",

  ETL_INFO_UPDATE_SUCCESS: "ETL_INFO_UPDATE_SUCCESS",
  ETL_INFO_UPDATE_ERROR: "ETL_INFO_UPDATE_ERROR",
  ETL_INFO_UPDATE_RESET: "ETL_INFO_UPDATE_RESET",

  ETL_ADD_SUCCESS: "ETL_ADD_SUCCESS",
  ETL_ADD_ERROR: "ETL_ADD_ERROR",

  ETL_DELETE_SUCCESS: "ETL_DELETE_SUCCESS",
  ETL_DELETE_ERROR: "ETL_DELETE_ERROR",
  ETL_DELETE_RESET: "ETL_DELETE_RESET",
  
  ETL_TIME_FORMAT_WRONG: "ETL_TIME_FORMAT_WRONG",

  ETL_ALREADY_EXIST: "ETL_ALREADY_EXIST",
  ETL_DOES_NOT_ALREADY_EXIST: "ETL_DOES_NOT_ALREADY_EXIST",

  RESET_ETL_UPDATE_VALUES: "RESET_ETL_UPDATE_VALUES"
}

export default EtlTableInfoType;